// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: dynamopb/dynamopb.proto

package dynamopb

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GSI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PartitionKey string `protobuf:"bytes,2,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	SortKey      string `protobuf:"bytes,3,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
}

func (x *GSI) Reset() {
	*x = GSI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamopb_dynamopb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GSI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSI) ProtoMessage() {}

func (x *GSI) ProtoReflect() protoreflect.Message {
	mi := &file_dynamopb_dynamopb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSI.ProtoReflect.Descriptor instead.
func (*GSI) Descriptor() ([]byte, []int) {
	return file_dynamopb_dynamopb_proto_rawDescGZIP(), []int{0}
}

func (x *GSI) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GSI) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *GSI) GetSortKey() string {
	if x != nil {
		return x.SortKey
	}
	return ""
}

var file_dynamopb_dynamopb_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "dynamopb.storable",
		Tag:           "varint,50001,opt,name=storable",
		Filename:      "dynamopb/dynamopb.proto",
	},
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: ([]*GSI)(nil),
		Field:         50002,
		Name:          "dynamopb.global_secondary_indexes",
		Tag:           "bytes,50002,rep,name=global_secondary_indexes",
		Filename:      "dynamopb/dynamopb.proto",
	},
}

// Extension fields to descriptor.MessageOptions.
var (
	// optional bool storable = 50001;
	E_Storable = &file_dynamopb_dynamopb_proto_extTypes[0]
	// repeated dynamopb.GSI global_secondary_indexes = 50002;
	E_GlobalSecondaryIndexes = &file_dynamopb_dynamopb_proto_extTypes[1]
)

var File_dynamopb_dynamopb_proto protoreflect.FileDescriptor

var file_dynamopb_dynamopb_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x70, 0x62, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x6f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x6f, 0x70, 0x62, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x03, 0x47, 0x53, 0x49, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79,
	0x3a, 0x3d, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x3a,
	0x6a, 0x0a, 0x18, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x61, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2, 0x86, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x70, 0x62, 0x2e,
	0x47, 0x53, 0x49, 0x52, 0x16, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x61, 0x72, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x42, 0x38, 0x5a, 0x36, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x74, 0x74, 0x2d, 0x70,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x67, 0x6f, 0x2d, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x64, 0x62, 0x2f, 0x64, 0x79, 0x6e,
	0x61, 0x6d, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dynamopb_dynamopb_proto_rawDescOnce sync.Once
	file_dynamopb_dynamopb_proto_rawDescData = file_dynamopb_dynamopb_proto_rawDesc
)

func file_dynamopb_dynamopb_proto_rawDescGZIP() []byte {
	file_dynamopb_dynamopb_proto_rawDescOnce.Do(func() {
		file_dynamopb_dynamopb_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynamopb_dynamopb_proto_rawDescData)
	})
	return file_dynamopb_dynamopb_proto_rawDescData
}

var file_dynamopb_dynamopb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dynamopb_dynamopb_proto_goTypes = []interface{}{
	(*GSI)(nil),                       // 0: dynamopb.GSI
	(*descriptor.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_dynamopb_dynamopb_proto_depIdxs = []int32{
	1, // 0: dynamopb.storable:extendee -> google.protobuf.MessageOptions
	1, // 1: dynamopb.global_secondary_indexes:extendee -> google.protobuf.MessageOptions
	0, // 2: dynamopb.global_secondary_indexes:type_name -> dynamopb.GSI
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dynamopb_dynamopb_proto_init() }
func file_dynamopb_dynamopb_proto_init() {
	if File_dynamopb_dynamopb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynamopb_dynamopb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GSI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynamopb_dynamopb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_dynamopb_dynamopb_proto_goTypes,
		DependencyIndexes: file_dynamopb_dynamopb_proto_depIdxs,
		MessageInfos:      file_dynamopb_dynamopb_proto_msgTypes,
		ExtensionInfos:    file_dynamopb_dynamopb_proto_extTypes,
	}.Build()
	File_dynamopb_dynamopb_proto = out.File
	file_dynamopb_dynamopb_proto_rawDesc = nil
	file_dynamopb_dynamopb_proto_goTypes = nil
	file_dynamopb_dynamopb_proto_depIdxs = nil
}
